### ISSUE TITLE
image and action columns

### ISSUE THREAD

**Issue by andreassteffen** [lineupjs/lineupjsx#10]
hi,
some questions:

1.  Does the react wrapper allow to add image (from a url-link) as well as action columns?
2. How do I define that a column should be used for sorting?
3. How do I define that a column (e.g. a clustering column) should be used for stratification?
4. Can a column have cells in the rows that contain an array of e.g. 100 float numbers and display as a heatmap?

Many thanks

**Comment by sgratzl** [comment]
requires: v1.0.0-beta.12

https://codepen.io/sgratzl/pen/RyvRVV?editors=0010

**Comment by andreassteffen** [comment]
thanks a lot!!! it works:
![image](https://user-images.githubusercontent.com/1114010/40283375-571d22d2-5c7d-11e8-96bd-e0c785edb99d.png)
however, when i collapse it looks like this:
![image](https://user-images.githubusercontent.com/1114010/40283381-6d1c5d00-5c7d-11e8-8fab-907d8122dafd.png)

questions:
1. Can I customize what is shown in the CANONICAL_SMILES image render column when grouping. 
2. How does the aggregation work? Does it show the min val? Can I customize this behaviour?

**Comment by sgratzl** [comment]
1. -> set the `groupRenderer="default" to change the default or interactive via the visualization menu entry
2. of the numbers column? -> for visualization options, see the visualization menu entry, for changing the way how the items are aggregated change the sortmethod of the col.umn in the menu

**Comment by andreassteffen** [comment]
sorry regarding 2 - too late: How does the aggregation for the array column (KINASE_SEL) work? but i understand now.thanks.
regarding 1. it means can I pass a custom function to groupRenderer that receives the rows of the group and returns e.g. an image which is then shown in group collapse?
a new question:
a) how can I define the colors of the categorical column CLUSTER (e.g. colorMap={{c1:'red',c2:'blue'}} )

**Comment by sgratzl** [comment]
> a) how can I define the colors of the categorical column CLUSTER (e.g. colorMap={{c1:'red',c2:'blue'}} )

I updated the code pen

**Comment by andreassteffen** [comment]
in https://codepen.io/sgratzl/pen/RyvRVV?editors=0010 ?

**Comment by sgratzl** [comment]
sorry https://codepen.io/sgratzl/pen/zjeLRO

also includes a custom image group renderer example

**Comment by andreassteffen** [comment]
thanks a lot! it's really a powerful library!
