### ISSUE TITLE
Lineupjsx couldn't render the list

### ISSUE THREAD

**Issue by crcrcry** [lineupjs/lineupjsx#11]
* Release number or git hash: 1.0.0-beta.11
 * Web browser version and OS: macos 10.13.3 chrome 67

### Steps to reproduce
 1. This is my code. I want to show a lineup demo in my browser
```javascript
import React, { Component } from 'react';
import LineUp from 'lineupjsx'
import 'lineupjsx/build/LineUpJSx.css'
import './App.css'

class App extends Component {
  state = {
    arr: []
  }
  componentDidMount () {
    const arr = []
    for (let i = 0; i < 100; i++) {
      arr.push({
        attr1: Math.random() * 10,
        attr2: Math.random() * 10,
        attr3: Math.random() * 10,
      })
    }
    this.setState({ arr: arr })
  }
  render() {
    return (
      <div className="App">
        <div id="lineup">
          <h2>This is a Lineup list</h2>
          <div id="list">
            <LineUp data={this.state.arr} />
          </div>
        </div>
      </div>
    );
  }
}

export default App;
```

### Observed behavior
- Browser result: 
![wechatimg401](https://user-images.githubusercontent.com/19330440/41350131-abd95d2a-6f44-11e8-8b2c-816de9de2b68.jpeg)

- Chrome dev tool consoles a error:
![wechatimg402](https://user-images.githubusercontent.com/19330440/41350138-af0d2a12-6f44-11e8-84b8-1d6ce679e804.jpeg)

### Expected behavior
 - I want to show a lineup demo by react and lineupjsx

**Comment by sgratzl** [comment]
please ensure that you specify for LineUp a certain height, since it doesn't have a height by its own. 

see https://codepen.io/sgratzl/pen/mXEpMP

**Comment by crcrcry** [comment]
Thank you!!
