### ISSUE TITLE
Visibility on Column (Question)

### ISSUE THREAD

**Issue by ahoak** [lineupjs/lineupjsx#13]
Is there a way to change visibility of a column to visible by default? The default right now is hover. I have tried <LineUpNumberColumnDesc style={{visibility: 'visible'}} ... /> but no luck. 

Here is an example where End Date and Start Date are not visible unless hovering:
![lineupjs_vis](https://user-images.githubusercontent.com/21273003/41946132-af729584-7965-11e8-8464-531527c265cd.PNG)

Thanks!

**Comment by sgratzl** [comment]
see https://codepen.io/sgratzl/pen/WyaxME?editors=0010

1. you should define the date as a date column -> `<LineUpDateColumnDesc ..`
1. you can change the default renderer for a column by using the `renderer` attribute, see also the `Visualzation` menu entry of the column

**Comment by ahoak** [comment]
Okay perfect! Thank you!
