### ISSUE TITLE
main div has 0 height, causing no rows rendering

### ISSUE THREAD

**Issue by haihan-lin** [lineupjs/lineupjsx#15]
Version: 1.0.7
Here is an example of the code:
https://github.com/angelicalin/LineUpExample

* Issue: 

main div has 0 height, which cause the web app only has the header and the side bar, but no rows.

* Attempt to fix: 

Tried FireFox and Chrome, issue still exist. 
Manually trying to input the height in Chrome inspect does not help either. 
Tried the LineUpJS implementation instead of react wrapper, the issue still exist.

**Comment by sgratzl** [comment]
LineUp automatically adapts to the given height but not enforcing a minimal height except for the header. Thus, you have to make sure that the lineup element uses all the available space. 

e.g. in https://codepen.io/sgratzl/pen/mXEpMP

look at the CSS class of the lu-wrapper element, the CSS of the codepen ensures that it takes all the available height

![2020-02-10 18_41_01-DevTools - codepen io_sgratzl_pen_mXEpMP](https://user-images.githubusercontent.com/4129778/74200506-20790080-4c35-11ea-9134-19c3e288c2c3.png)

**Comment by haihan-lin** [comment]
But is there something I specifically need to do to let it takes in height? Because the example code I put in there is basically just tutorial. I didn't change anything and the main div has 0 height.

**Comment by haihan-lin** [comment]
Ok I got it now. So adding specific css lines for divs is required.
