### ISSUE TITLE
Data rows and control sidebar not rendered

### ISSUE THREAD

**Issue by mccalluc** [lineupjs/lineupjsx#26]
* Release number or git hash: 4.0.0
 * Web browser version and OS: Firefox 91.0.2 

### Steps to reproduce

 1. Checkout code from https://github.com/hubmapconsortium/portal-ui/pull/2112
 2. Run `./dev-start.sh`
 3. Look at http://localhost:5001/lineup/donors

### Observed behavior
 * Lots of `Cannot find SourceMap` warnings
 * No rows of data
 * No right-hand sidebar

### Expected behavior
 * No warnings
 * Many rows of data
 * control sidebar on the right-hand-side

<img width="1136" alt="Screen Shot 2021-08-31 at 1 12 51 PM" src="https://user-images.githubusercontent.com/730388/131546903-75d3d6c4-2728-4c47-8356-207f89deea0e.png">
 
Also, is there a way to use this without depending on a CDN for the CSS?

**Comment by sgratzl** [comment]
looking at https://unpkg.com/browse/lineupjsx@4.0.0/build/ it both contains the CSS file and the source map files. Not sure whether they are corrected packed on your side. 

regarding LineUp: Please make sure to assign some vertical space to LineUp. LineUp fits its given space with rows. In your case, LineUp is assigned no vertical space, thus no rows are rendered.

**Comment by mccalluc** [comment]
- Importing the styles works.
- Adding `.lu-wrapper { height: 90vh; }` fixed the rendering -- Worth mentioning in the README?

I'll go ahead and close this: apologies if that's not the practice you prefer.

I'll open a new issue for an apparent race condition when dealing with a large number of columns.
