### ISSUE TITLE
Large number of columns has inconsistent rendering.

### ISSUE THREAD

**Issue by mccalluc** [lineupjs/lineupjsx#27]
* Release number or git hash: 4.0.0
 * Web browser version and OS: Firefox 91.0.2 

### Steps to reproduce

 1. Checkout code from https://github.com/hubmapconsortium/portal-ui/pull/2112
 2. Run `./dev-start.sh`
 3. Look at http://localhost:5001/lineup/datasets

### Observed behavior
This view has a pathologically large number of columns...
```
uuid	hubmap_id	ablation_distance_between_shots_x_units	ablation_distance_between_shots_x_value	ablation_distance_between_shots_y_units	ablation_distance_between_shots_y_value	ablation_frequency_unit	ablation_frequency_value	acquisition_id	acquisition_instrument_model	acquisition_instrument_vendor	analyte_class	assay_category	assay_type	bulk_atac_cell_isolation_protocols_io_doi	bulk_rna_isolation_protocols_io_doi	bulk_rna_isolation_quality_metric_value	bulk_rna_yield_units_per_tissue_unit	bulk_rna_yield_value	bulk_transposition_input_number_nuclei	cell_barcode_offset	cell_barcode_read	cell_barcode_size	data_collection_mode	data_precision_bytes	description	dna_assay_input_unit	dna_assay_input_value	dual_count_start	end_datetime	execution_datetime	gdna_fragmentation_quality_assurance	increment_z_unit	increment_z_value	is_targeted	is_technical_replicate	labeling	lc_column_model	lc_column_vendor	lc_flow_rate_unit	lc_flow_rate_value	lc_gradient	lc_id_unit	lc_id_value	lc_instrument_model	lth_unitulc_length_value	lc_mobile_phase_a	lc_mobile_phase_b	lc_resin	lc_temp_unit	lc_temp_value	library_adapter_sequence	library_average_fragment_size	library_concentration_unit	library_concentration_value	library_construction_method	library_construction_protocols_io_doi	library_creation_date	library_final_yield	library_final_yield_unit	library_final_yield_value	library_id	library_layout	library_pcr_cycles	library_pcr_cycles_for_sample_index	library_preparation_kit	max_x_width_unit	max_x_width_value	max_y_height_unit	max_y_height_value	ms_scan_mode	ms_source	mz_range_high_value	mz_range_low_value	number_of_antibodies	number_of_barcode_probes	number_of_barcode_regions_per_barcode_probe	number_of_channels	number_of_cycles	number_of_pseudocolors_per_channel	number_of_readout_probes_per_channel	operatoroperator_email	overall_protocols_io_doi	pi	pi_email	polarity	preparation_instrument_model	preparation_instrument_vendor	preparation_maldi_matrix	preparation_type	processing_protocols_io_doi	processing_search	protocols_io_doi	range_z_unit	range_z_value	reagent_prep_protocols_io_doi	resolution_x_unit	resolution_x_value	resolution_y_unitresolution_y_value	resolution_z_unit	resolution_z_value	rnaseq_assay_input	rnaseq_assay_input_unit	rnaseq_assay_input_value	rnaseq_assay_method	roi_description	roi_id	sample_quality_metric	sc_isolation_cell_number	sc_isolation_enrichment	sc_isolation_entity	sc_isolation_protocols_io_doi	sc_isolation_quality_metric	sc_isolation_tissue_dissociation	section_prep_protocols_io_doi	segment_data_format	sequencing_phix_percent	sequencing_read_format	sequencing_read_percent_q30	sequencing_reagent_kit	signal_type	stain	start_datetime	step_z_value	transposition_input	transposition_kit_number	transposition_method	transposition_transposase_source
```

(Full TSV can be downloaded from https://portal.hubmapconsortium.org/api/v0/datasets.tsv)

About half the time it renders like:
<img width="1023" alt="Screen Shot 2021-09-01 at 10 52 25 AM" src="https://user-images.githubusercontent.com/730388/131696047-f3861e07-cf17-476f-9851-c96fbe86c57d.png">

and half the time it renders like:
<img width="1023" alt="Screen Shot 2021-09-01 at 10 55 38 AM" src="https://user-images.githubusercontent.com/730388/131696092-4b6b58b5-02d8-4c84-8788-be10e0b28a67.png">

Same approximately 50/50 behavior on Chrome.

### Expected behavior
 * Consistently render like the second screenshot.

**Comment by sgratzl** [comment]
can you verify some things for me please:
 1. does the input data in both cases look the same (especially the first row)? e.g. by logging the data and check whether it is the same in both cases
 2. does the Add Column on the right lists all columns in both cases or does it list a different set? if it is the same, the same columns were derived but LineUp is showing a different subset. If it is different the problem is earlier.
 3. is there some horizontal scrolling available in both cases (especially the first one)?

Moreover, I would enforce the column names and order to be extracted by specifying `deriveColumns={['column 1', 'column 2', ...]}`. Otherwise, you are dependent on the order returned by `Object.keys(rows[0])`

**Comment by mccalluc** [comment]
Thanks for the help: I've got the logging in place now.
- My theory about a large number of columns is a red herring.
- The problem might be in the database I'm relying on: Still debugging.
- I didn't know that the first row would determine the columns displayed. Worth adding to readme?

**Comment by mccalluc** [comment]
My best guess is that there was a tie on the sort key, and one of the tied records just didn't have any metadata, and it inferred that to be true of all. Thanks for the pointer. Closing.
