### ISSUE TITLE
create-react-app requires ES5 precompilation

### ISSUE THREAD

**Issue by moritzschaefer** [lineupjs/lineupjsx#3]
* Release number or git hash: 
 * Web browser version and OS: 

### Steps to reproduce

 1. Use lineupjsx in your create-react-app project
 1. Run "npm run build"

### Observed behavior

    npm run build

fails:

> └─(14:56:54 on master ✹ ✭)──> npm run build                                                                                                              ──(Mo,Apr30)─┘
> 
> > webapp@0.1.0 build /home/moritz/Projects/credit/webapp
> > react-scripts-ts build
> 
> Creating an optimized production build...
> Warning: The 'no-use-before-declare' rule requires type information.
> ts-loader: Using typescript@2.6.1 and /home/moritz/Projects/credit/webapp/tsconfig.json
> Failed to compile.
> 
> Failed to minify the code from this file:
> 
>         ./node_modules/lineupjsx/build/LineUpJSx.js:1:2190
> 
> Read more here: http://bit.ly/2tRViJ9
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! webapp@0.1.0 build: `react-scripts-ts build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the webapp@0.1.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> 
>    ╭─────────────────────────────────────╮
>    │                                     │
>    │   Update available 5.8.0 → 6.0.0    │
>    │     Run npm i -g npm to update      │
>    │                                     │
>    ╰─────────────────────────────────────╯
> 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/moritz/.npm/_logs/2018-04-30T12_57_29_387Z-debug.log
> 

### Expected behavior
 
Does not fail. 

create-react-app (http://bit.ly/2tRViJ9) states, that all third party libs need to be precompiled to ES5. 

Is that feasible?

**Comment by sgratzl** [comment]
actually should be es5

https://github.com/sgratzl/lineupjsx/blob/master/tsconfig.json#L4

**Comment by sgratzl** [comment]
I will check what is going on

**Comment by sgratzl** [comment]
should be fixed with v1.0.0-beta.9, seems like an dependency issue that the wrong build was used
