### ISSUE TITLE
Compilation error in lineupengine

### ISSUE THREAD

**Issue by moritzschaefer** [lineupjs/lineupjsx#8]
* Release number or git hash: v1.0.0-beta.9
 * TS: 2.8.3

### Steps to reproduce

 1. Start a new project with create-react-app
 2. Use boilerplate code from README.md to insert a LineUp
 3. Run npm start or npm run build

### Observed behavior

Doesn't compile. Observed errors:

> /home/moritz/Projects/credit/webapp/node_modules/lineupengine/build/typings/table/internal/ACellAdapter.d.ts
> (7,16): error TS2304: Cannot find name 'ACellAdapter'.
> 
> /home/moritz/Projects/ts-test/node_modules/lineupengine/build/typings/ARowRenderer.d.ts
> (5,10): Module '"/home/moritz/Projects/ts-test/node_modules/lineupengine/build/typings/internal/index"' has no exported member 'IDelayedMode'.

### Expected behavior
 Compiles

**Comment by sgratzl** [comment]
fixed as part of v1.0.0-beta.11

**Comment by moritzschaefer** [comment]
confirmed. thank you!
