### ISSUE TITLE
cannot get lineupsjsx component to work

### ISSUE THREAD

**Issue by andreassteffen** [lineupjs/lineupjsx#9]
* Release number or git hash: 
 * Web browser version and OS: 
chrome Version 65.0.3325.181/macOS
### Steps to reproduce
1. generate react app using create-react-app
2. use minimal usage example code from https://github.com/datavisyn/lineupjsx
```
class App extends Component {
    render() {

// generate some data
        const arr = [];
        const cats = ['c1', 'c2', 'c3'];
        for (let i = 0; i < 50; ++i) {
            arr.push({
                a: Math.random() * 10,
                d: 'Row ' + i,
                cat: cats[Math.floor(Math.random() * 3)],
                cat2: cats[Math.floor(Math.random() * 3)]
            })
        }
        return (
            <div className="App">
                <LineUp data={arr}/>
            </div>
        );
    }
}
```

### Observed behavior
* only see 
![image](https://user-images.githubusercontent.com/1114010/40023961-0bd807ba-57cd-11e8-8b12-71ef46dfce28.png)
* console output:
```
LineUpJSx.js:1 Uncaught TypeError: Cannot read property 'scrollLeft' of null
    at Ac.recreate (LineUpJSx.js:1)
    at Ac.render (LineUpJSx.js:1)
    at t.forEach (LineUpJSx.js:1)
    at Array.forEach (<anonymous>)
    at Ic.update (LineUpJSx.js:1)
    at Object.e.on (LineUpJSx.js:1)
    at S.apply (LineUpJSx.js:1)
    at i (LineUpJSx.js:1)
    at xc.fireImpl (LineUpJSx.js:1)
    at xc.fire (LineUpJSx.js:1)
    at xc.fire (LineUpJSx.js:1)
    at Object.Ac.delayedUpdate.n (LineUpJSx.js:1)
    at setTimeout (LineUpJSx.js:1)
```

**Comment by sgratzl** [comment]
1. you have to give the container a specific height, since lineup adapts to the available space but itself don't need a minimum height
2. cannot reproduce the error: https://codepen.io/sgratzl/pen/zjJPdd?editors=0110

**Comment by sgratzl** [comment]
see also https://github.com/sgratzl/lineupjsx-test and https://github.com/sgratzl/lineupjsx-test/blob/master/src/App.css#L6

**Comment by andreassteffen** [comment]
example works here aswell. my code was at v1.0.0-beta.8. I now move to v1.0.0-beta.9 and it's working now aswell.
thanks a lot!
